// GENERATED by scripts/sync-icons.mjs — do not edit by hand.
// Run `pnpm icons:sync` to regenerate.
/**
 * How each packaged icon is painted.
 *
 * This map CLASSIFIES; it does not gate availability. A name that is
 * absent falls through to the `<img>` + initials path, which is what
 * keeps consumer-supplied SVGs under `public/icons/` working.
 *
 * Keyed by `${folder}/${resolvedName}` — the folder matters because
 * `apple` exists under both `stacks/` and `platforms/`.
 */
export type IconKind = 'color' | 'mono';

export const ICON_KINDS: Readonly<Record<string, IconKind>> = {
  'platforms/android': 'color',
  'platforms/app': 'mono',
  'platforms/chrome': 'color',
  'platforms/desktop': 'mono',
  'platforms/embedded': 'mono',
  'platforms/ios': 'mono',
  'platforms/linux': 'color',
  'platforms/macos': 'mono',
  'platforms/ubuntu': 'color',
  'platforms/web': 'mono',
  'platforms/windows': 'color',
  'stacks/android': 'color',
  'stacks/apple': 'mono',
  'stacks/bun': 'color',
  'stacks/capacitor': 'color',
  'stacks/clojure': 'color',
  'stacks/dart': 'color',
  'stacks/deno': 'mono',
  'stacks/django': 'color',
  'stacks/docker': 'color',
  'stacks/firebase': 'color',
  'stacks/flutter': 'color',
  'stacks/go': 'color',
  'stacks/graphql': 'color',
  'stacks/ionic': 'color',
  'stacks/java': 'color',
  'stacks/javascript': 'color',
  'stacks/kotlin': 'color',
  'stacks/llm': 'mono',
  'stacks/mongodb': 'color',
  'stacks/nodejs': 'color',
  'stacks/python': 'color',
  'stacks/rag': 'mono',
  'stacks/react': 'color',
  'stacks/react-native': 'color',
  'stacks/rust': 'mono',
  'stacks/solidity': 'mono',
  'stacks/sveltekit': 'color',
  'stacks/swift': 'color',
  'stacks/tauri': 'mono',
  'stacks/tensorflow': 'color',
  'stacks/typescript': 'color',
  'stacks/vue': 'color',
};
